# Generated by Django 4.1.3 on 2022-11-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerist', '0009_alter_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
