# Generated by Django 4.1.3 on 2022-11-20 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggerist', '0012_profile_facebook_url_profile_instagram_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website_url',
        ),
    ]
